name: stik_vendas
description: "A new Flutter project."

publish_to: 'none' 


environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  cupertino_icons: ^1.0.2
  fl_chart: ^0.66.0
  pie_chart: ^5.4.0
  carousel_slider: ^4.2.1
  mvc_pattern: ^8.12.0
  awesome_dialog: ^3.2.0
  syncfusion_flutter_charts: ^24.1.46+1
  d_chart: ^2.6.7
  percent_indicator: ^4.2.3
  mask_text_input_formatter: ^2.8.0
  cloud_firestore: ^4.15.8
  http: 1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/Logo_Stik_App.png
  #fonts:
    #- family: Montserrart Regular
     # fonts:
        #- asset: assets/fonts/mo_re.ttf

