name: stik_vendas
description: "A new Flutter project."

publish_to: 'none' 


environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  cupertino_icons: ^1.0.2
  fl_chart: ^0.66.0
  pie_chart: ^5.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/Logo_Stik_App.png
  #fonts:
    #- family: Montserrart Regular
     # fonts:
        #- asset: assets/fonts/mo_re.ttf

