name: stik_vendas
description: "A new Flutter project."

publish_to: 'none' 


environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  cupertino_icons: ^1.0.2
  fl_chart: ^0.66.0
  pie_chart: ^5.4.0
  google_nav_bar: ^5.0.6
  fancy_bottom_navigation: ^0.3.3
  lottie: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_carousel_widget: ^2.2.0
  pagination_view: ^2.0.0
  http: ^1.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  mvc_pattern: ^8.12.0
  awesome_dialog: ^3.2.0
  syncfusion_flutter_charts: ^24.1.46+1
  d_chart: ^2.6.7
  percent_indicator: ^4.2.3
  intl: ^0.18.1
  mask_text_input_formatter: ^2.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/Logo_Stik_App.png
  #fonts:
    #- family: Montserrart Regular
     # fonts:
        #- asset: assets/fonts/mo_re.ttf

